version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2404:2024.05.1

workflows:
  main:
    jobs:
      - go-lint
      - run-devnet-tests:
          matrix:
            parameters:
              args-file:
                - ./systems/kurtosis/barebones_devnet.yaml

commands:
  install-dependencies:
    steps:
      - run:
          name: Install mise
          command: curl https://mise.run | MISE_INSTALL_PATH=/home/circleci/bin/mise sh
      - run:
          name: Activate mise
          command: echo 'eval "$(mise activate bash)"' >> $BASH_ENV
      - run:
          name: Install mise dependencies
          command: mise install

  install-go-modules:
    parameters:
      from:
        description: Path to go.sum file
        type: string
        default: go.sum
      path:
        description: Go module cache path
        type: string
        default: /home/circleci/.go_workspace/pkg/mod
      version:
        description: Version (cache breaker)
        type: string
        default: v1
    steps:
      - restore_cache:
          name: Restore Go modules cache
          keys:
            - go-mod-{{ arch }}-{{ checksum "<< parameters.from >>" }}-<< parameters.version >>
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-{{ arch }}-{{ checksum "<< parameters.from >>" }}-<< parameters.version >>
          paths:
              - << parameters.path >>

  start-kurtosis-devnet:
    parameters:
      args-file:
        type: string
        description: Path to kurtosis args file
      enclave-name:
        type: string
        description: Kurtosis enclave name
        default: devnet
      package:
        type: string
        description: Kurtosis package to use
        default: github.com/ethpandaops/optimism-package
    steps:
      - run:
          name: Run kurtosis barebones devnet
          command: kurtosis run --enclave << parameters.enclave-name >> << parameters.package >> --args-file << parameters.args-file >>
      - run:
          name: Export devnet-sdk environment URL
          command: echo "export DEVNET_ENV_URL=ktnative://<< parameters.enclave-name >>$(realpath << parameters.args-file >>)" >> $BASH_ENV
      - run:
          name: Show devnet-sdk environment URL
          command: echo "Using devnet environment from $DEVNET_ENV_URL"

jobs:
  go-lint:
    executor: default
    steps:
      - checkout
      - install-dependencies
      - install-go-modules
      - run:
          name: Check go.mod
          command: |
            just tidy
            git diff --exit-code
      - run:
          name: Run lint
          command: just lint
  
  run-devnet-tests:
    executor: default
    parameters:
      args-file:
        type: string
        description: Path to kurtosis args file
    steps:
      - checkout
      - install-dependencies
      - install-go-modules
      - start-kurtosis-devnet:
          args-file: << parameters.args-file >>
      - run:
          name: Run tests
          command: just test
            